import type { TierList } from '@/types';
import { TIERS } from '@/config';

interface CharacterMappingData {
  formId: string;
  characterToEntry: Record<string, string>;
}

/**
 * Character-to-entry-ID mapping loaded at runtime.
 * Generated by scripts/generate-form-mapping.ts from Google Form pre-fill URL.
 */
let mappingData: CharacterMappingData | null = null;

async function loadCharacterMapping(): Promise<CharacterMappingData> {
  if (mappingData !== null) {
    return mappingData;
  }

  const response = await fetch(`${import.meta.env.BASE_URL}form-character-mapping.json`);
  if (!response.ok) throw new Error('Failed to load form-character-mapping.json');

  const data = await response.json();
  mappingData = {
    formId: data.formId,
    characterToEntry: data.characterToEntry || {},
  };
  return mappingData;
}

/**
 * Builds a Google Form pre-filled viewform URL with all tier answers encoded.
 *
 * Uses the viewform pre-fill approach instead of direct POST because Google Forms
 * with "Require sign-in" uses CSRF tokens (token + tag) that are only available
 * after loading the form page — impossible to obtain cross-origin.
 *
 * The user opens the pre-filled form in a new tab and clicks Submit once.
 * Google handles authentication and CSRF internally.
 */
export async function buildPrefilledUrl(tierList: TierList): Promise<string> {
  const { formId, characterToEntry } = await loadCharacterMapping();

  const params = new URLSearchParams({ usp: 'pp_url' });

  for (const tier of TIERS) {
    const characters = tierList[tier as keyof typeof tierList];
    for (const character of characters) {
      const entryId = characterToEntry[character.id];
      if (entryId) {
        params.append(entryId, tier);
      } else {
        console.warn(`[Form] No entry ID for character: ${character.id}`);
      }
    }
  }

  return `https://docs.google.com/forms/d/e/${formId}/viewform?${params.toString()}`;
}

/**
 * Opens a pre-filled Google Form in a new tab for the user to confirm and submit.
 * Returns the pre-filled URL that was opened.
 */
export async function submitTierListForm(tierList: TierList): Promise<string> {
  const url = await buildPrefilledUrl(tierList);
  console.log('[Form] Opening pre-filled form:', url.slice(0, 80) + '...');
  window.open(url, '_blank', 'noopener,noreferrer');
  return url;
}

/**
 * Validate that tier list is complete before submission
 */
export function validateTierListCompletion(
  tierList: TierList,
  totalCharacters: number
): { isValid: boolean; error?: string } {
  const assignedCount = TIERS.reduce((sum, tier) => {
    return sum + tierList[tier as keyof typeof tierList].length;
  }, 0);

  if (assignedCount !== totalCharacters) {
    return {
      isValid: false,
      error: `Please assign all ${totalCharacters} characters to tiers. Currently assigned: ${assignedCount}`,
    };
  }

  return { isValid: true };
}

/**
 * Generate a human-readable summary of the tier list for preview
 */
export function generateTierListSummary(tierList: TierList): string {
  const lines: string[] = [];

  for (const tier of TIERS) {
    const characters = tierList[tier as keyof typeof tierList];
    const count = characters.length;
    const names = characters.map((c) => c.name).join(', ');

    lines.push(`${tier} Tier (${count}): ${names || 'None'}`);
  }

  return lines.join('\n');
}

